### ISSUE TITLE
Over/Undertime

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#100]
Would be nice to have the total time of all events somewhere to see if you´re running short or too long... Useful for Streamingevents where you need to stay in defined times.

**Comment by cpvalente** [comment]
Hey @Keksstar, thank you for your suggestion.
It sounds good to me, could you please describe the feature a bit more in depth?
- Would it be just a sum of all existing timers?
- How would it handle the current delay feature?
- Is this related to roll mode only?
- What is the format of the information and in what context should it appear (in the app? in some of the screens?)

Thank you again, there is some other work planned related to timers and I can probably fit this in there

**Comment by Keksstar** [comment]
Hi @cpvalente , thanks for the fast reply!

In general I see this as an additonal mode.

Lets say we have an Event with Start 8pm, End 10pm given with four speakers.
Speaker 1 has 30min
Speaker 2 has 30min
Speaker 3 has 30min
Speaker 4 has 30min

We start timer for speaker 1, he´s really fast and only needs 20min. This creates an undertime of 10min. - This is something the director needs to know and also it´s nice to know for the speaker that he doesn´t need to hurry. So both should see it. (and all others in the backoffice) - But it´s not an public information. (should be displayed as "-10min")
Speaker 2 loves his work, and talks full 60min. This creates an overtime of +20min as we already had 10min undertime and he wasted this time completly....
So only 40min left for Speaker 3+4.
and so on, I think you get the point.

The beginning time of the next event should automatically adjusted.
Let´s say Speaker 1 starts at 8pm and has 30min, Speaker 2 start at 8:30pm... but now Speaker 1 needs 35min, so the new starting time for Speaker 2 adjusts itself to 8:30+5=8:35pm
Or vice versa when he´s faster.
Also times needs to be adjusted if you skip or delete an entry.


So to answer your question:
- nope, see above
- Delay is just an "break", it´s like any other entry. It just get´s summed up with all other elements
- Nope, it´s way more than this - it´s an new mode.
- Sure in the app and on the screens that are not public.

I would like to use ontime as something similar like Shoflo, but with much less functionality.
It´s not just Speaker times, it´s everything of the event:
Intro time
Host time
VT time
Speaker time
Break time
etc.

This in sum is what I would like to use ontime for.
So Ontime could become the "master-timing-device" for an event. And maybe it can output defined OSC messages in the future, so you can even use this to trigger events like playing VTs. - and everyone in the Team can see how long this VT is to tidy up the stage :-)

**Comment by Keksstar** [comment]
@cpvalente - too complex? ;-))

**Comment by cpvalente** [comment]
I can imagine this would be possible with the current architecture and it sounds to me like a good addition to the feature set.
I guess some new mode that accumulate times. 

However I wouldn't expect this to be in development in the near future as there are other features being prioritised (HTTP and OSC integration, Mac OS, cue sheets)

**Comment by Keksstar** [comment]
Any chance to bump this to the top of the roadmap? :-)

**Comment by cpvalente** [comment]
Hi @Keksstar,

I am preparing release of v1 (sometime in the next few days).
From there I feel the most important improvements are the discussed event block improvements #55 

I am still unclear on how this new mode would work, but improvements in delay mode will follow straight after

**Comment by compgeek35610** [comment]
After having a play with ontime on an event, I was able to achieve this result with adding a block before going to a break in the show, and adding a delay after each speaker with a positive or negative time depending on how close they were to their allocated slot.

Perhaps this could be implemented quite simply by having an option for delays to be automatically added after each event when it is advanced if the timer has more than one minute remaining or is more than one minute overtime, provided the timer has been started for that event?

This would allow tracking by adding up the total delay time since the last block to determine if you are ahead or behind on time, and see your expected finish time in your rundown.

I found it to be very useful information, but manually adding the delay blocks was a cumbersome workflow - having this automated would be a game changer.

**Comment by cpvalente** [comment]
Hi @compgeek35610, thank you for reaching out.

This is a big part of the restructures planned in the roadmap and a big reason for v2.
We will move on to these kinds of behaviours once v2 has left open beta (still in closed alpha as of now)

**Comment by compgeek35610** [comment]
I suspected this may have made it to the v2 roadmap, with any luck my workaround method is sufficient for others who might want to track their events overtime in the interim period.

Appreciate all the work you and others are doing for v2 and have done to get ontime into the world, this sort of powerful tool being open source and available to the world is fantastic!

Please feel free to reach out should you need further alpha/beta testers ahead of the big launch, I’d be happy to assist the project however I can, but my pull requests would cause more harm than good!

**Comment by cpvalente** [comment]
Thank you!

Collaborators are very welcome, both in testing and coding. 

We are currently in the 4th round of alpha testing. I believe we will follow to closed beta after this.
We have also worked to restructure the project to make it easier for other developers to write features. I hope that will help in the long run.

If you would like to contribute code-wise, you can get in touch with mail @ getontime.no. We can try and see how to coordinate it. There are several app improvements which could have a great effect to users and be developed with minimal react and CSS knowledge.

**Comment by cpvalente** [comment]
We are trying to nail down a workflow to be able to implement this feature.

### Likely requirements
From our rounds so far, this feature would look something like:
- The user has access to an interface modifier which will act on the play buttons (no roll mode)
- When this mode is active, when an event is finished, it will create a delay equal to the time remaining from its scheduled deadline (ie: scheduled end is 09:30 and the actual end is 09:25 would create a negative delay of 5 minutes). see Workflow A described below
- Since we might have several events which block a delay (deadlines) we would need a delay block positioned after every deadline event
- We would have some information at the top of the rundown and extra information in the info panel
- We need a way to communicate a hard deadline, this will also double act as a stop for the propagation of a delay
- We would communicate this delay with a single block, potentially positioned in the header of the rundown

### Trade-offs
- I believe we would need to reconsider our delay workflow, as it might cause conflicts with the above
- With the planned improvements on the time types (https://github.com/cpvalente/ontime/issues/59#issuecomment-1556218163 just start, just end, just duration). We could run into trouble having to calculate schedules based on some guesses. I would consider guessing, generally a bad thing for Ontime to do. Are these two features mutually exclusive? They are at least very much tied

**Comment by 12xx12** [comment]
My optimal workflow during the event would be one simple button press. A new button might be added or one repurposed. I would describe it as a "Next" button.

`a)` During roll mode: Confirm to go to the next item. This behavior should be optional for people which just want the hard roll mode.
`b)` Not rolling: When pressing the next button with over-/undertime, the time is converted to a delay and the next item is started.

Since I am using a stream deck support in the HTTP API is very useful for me.
In both cases the delay is applied like using the delay item.

For break events I imagine an event like this:
- It takes a single time which makes it a hard deadline.
- If a duration is added an option should be available if the item can be moved or if it should stay in place as a hard deadline. A pop-up could be added if the delay > end of deadline. This can move the hard deadline or suggest other options.

**Comment by cpvalente** [comment]
Hi @12xx12 , thank you for your help here

I was slightly side tracked by your comment

> Since I am using a stream deck support in the HTTP API is very useful for me.
Is there a reason not to use the OSC or websocket API? If there is, lets chat: the HTTP API can be improved

**Comment by compgeek35610** [comment]
Apologies for not getting back to you on this one, and congrats on V2

I haven’t played with the latest release yet, but an interesting idea could be a way to ‘lock’ any time and have it unaffected by upstream changes with the others sharing the load.

For example, I could lock the time we return from lunch and lock the duration of the pre lunch events, so that nobody’s time gets shortened and we come back on schedule, resulting in lunch being shortened.

Alternatively, I could lock lunch start time so we end as per schedule and also lock the CEOs speech duration, so if someone else runs over it deducts time from everyone except the CEO to get us back on track.

Just rambling for now, will have a play with V2 when I can and keen to continue discussions!

**Comment by cpvalente** [comment]
We have implemented a variation of this in v3 which we call `offset`. 

Will close this ticker for now, user wishing to provide suggestions for improvement should do so against the existing implementation
