### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#101]
The title says it all :-)

Would be nice to have (definable?) hotkeys for start, pause, stop, +- 1 min, etc...

**Comment by cpvalente** [comment]
I have envisioned that ontime would be headless as much as possible (apart from data entry). So you would integrate it with another controller over HTTP or OSC

however this doesn't sound unreasonable. I would stay away from keys like space bar and shift combinations as it can be triggered accidentally on data entry. Is there a key combination you would expect?

**Comment by cpvalente** [comment]
Hi @Keksstar 
Would it be possible that this request could be joined with #104 

I am worried about shortcuts in something that might run in a browser, especially since the expected shortcuts would be <spacebar> <Esc> and so on... However this feels safer on a separate screen with only playback.

What do you think?
What would those shortcuts look like?

**Comment by Keksstar** [comment]
They should be definable in an options menu... So everyone can set like they want...

**Comment by je71175** [comment]
Just a thought to add to this topic - custom keypad for onTime

https://www.maxkeyboard.com/max-falcon-8-rgb-custom-programmable-mini-macropad-mechanical-keyboard-assembled.html

**Comment by cpvalente** [comment]
Thank you @je71175 

This feature request is stale since there is no resolution on some of it possible edge cases.

With the ability to use the editor in the browser, there is a possible conflict with shortcuts.

There is an argument to make shortcuts only available in the app.

In my opinion the navigation should be under user control and take advantage of one of the APIs. I would prefer strengthening the API interface than creating features that serve a small subset of users

**Comment by cpvalente** [comment]
Closing for now
