### ISSUE TITLE
Count Up and Clock not clear in the editor timer

### ISSUE THREAD

**Issue by markvesterskov** [cpvalente/ontime#1024]
Just installed 3.10-alpha1 (also tried 3.04), and when i select Count Up or Clock the timer acts as a countdown. 

<img width="1711" alt="Skærmbillede 2024-05-31 kl  13 58 57" src="https://github.com/cpvalente/ontime/assets/7515900/b392e02e-26b3-4dde-b0c0-f6fba9124056">

**Comment by cpvalente** [comment]
> Just installed 3.10-alpha1 (also tried 3.04), and when i select Count Up or Clock the timer acts as a countdown. 
> 

Hi, thank you for reaching out.

The count-up timer affects the way times are displayed. You should see in the timer view that this is the case

However, in the editor all times count down so that you can keep track of the schedule. 

I agree that we should likely look into clarifying this behaviour.

Can you confirm that the behaviour I suggest is true? So you have any suggestions for how to display to the editor the count-up result of the timer?

**Comment by markvesterskov** [comment]
Confirmed! I had not opened the timer views, as i was super confused by the output in the editor tab.

I had expected, after selecting count up, that the counter would increment seconds instead of decrementing them, also in the editor.

Thanks for the fast reply.

**Comment by cpvalente** [comment]
No worries. 

I agree your expectations are reasonable. I will try and see if we can clarify in the editor
