### ISSUE TITLE
Public view with external iframe

### ISSUE THREAD

**Issue by sledzik1984** [cpvalente/ontime#1075]
Hi!
Thanks for great piece of software!

I have little idea regarding public view. It would be great to have another Public view that allows embedding of external html code to embed PiP with live stream. 

![New Project (1)](https://github.com/cpvalente/ontime/assets/1233199/2035b316-48d0-478a-9ff9-f4c73c185cc5)

**Comment by lukestein** [comment]
I'm of two minds here. On the one hand, this functionality looks very cool. On the other hand, this is arguably out of scope and I have no idea what if anything the implications are for e.g., the security model and UX.

One in-between possibility would be an HTML layout that reserved a physical spot for the external content, but required the user to render and overlay themselves using a switcher, OBS, or e.g., a digital signage solution (I use [slideshow.digital](https://slideshow.digital))

**Comment by cpvalente** [comment]
Hi @sledzik1984 and @lukestein 

We used to have such view in Ontime which worked as described by @lukestein 
https://ontime.gitbook.io/ontime-v1-old/views/pip

The issue with creating such views is that they are very specific to a presentation and lead to an overwhelming amount of user communication along the lines of "we need this other piece of information as well" or "we need the placeholder to be smaller / larger / wider"...

The decision to remove was that, since we did not have a vision for the view (every view in Ontime has been mapped to a production role that needs to achieve a task), we would instead provide tools for users to make their own.

This has been an under-used (and honestly under-documented) part of the app which I believe is very powerful. In my opinion, further efforts in view creation should consider unlocking workflows or facilitating user defined view layouts.

This was at least our position before, I am happy to revisit

**Comment by sledzik1984** [comment]
From my perspective PiP View is great for Green Room monitors. Every two weeks I'm running a online medical webcast with green room for speakers.  Each time we install one 55'' LCD with Ontime (public view) and another 55'' with video feed from studio. 

There are many video tools that could be used in such PiP view:
- Youtube, Vimeo, Wowza live streams 
- VMIX LiveLAN 
- RTSP Video streams. 

Of course I can buy and use some digital signage software and make an layout with Ontime in background  and video window on top of that but I think that if I could use only one program I will prefer that over using 2 programs :)

**Comment by jwetzell** [comment]
The current custom view  "system" would definitely be able to handle this but is not a trivial amount of work for an end user to make one. I think exploring user-defined layouts would be interesting, or having a couple of "example" custom views so people have something to get off the ground with.

**Comment by dfaligertwood** [comment]
My solution for when I don't want to code something has been to use Chataigne to create a dashboard and pull in data from ontime, then point to that dashboard. It seems to work fairly well.

**Comment by cpvalente** [comment]
Hi @sledzik1984, we had a look into this and decided that we will not prioritise this work.

If someone in the community were to propose an implementation I wouldnt be against it. However, it currently doesnt stack up against the ongoing roadmap.

Thank you for taking the time to bring forwards a suggestion, I hope this does not discourage you from doing so in future

**Comment by cpvalente** [comment]
Closing this ticket as not planned
