### ISSUE TITLE
v3.3.1 on Docker fails to start

### ISSUE THREAD

**Issue by Punkerschaf** [cpvalente/ontime#1090]
Tried to run v3.3.1 on Docker (Synology). Stops directly without error (`Exit Code 0`). V3.3.0 works fine with same config.
Log shows only code fragments. (Log exports as HTML so renamed it as TXT for github. Sorry for that.)

[log-ontime-3.3.1.html.txt](https://github.com/user-attachments/files/15864241/log-ontime-3.3.1.html.txt)

**Comment by juzz197** [comment]
Similar on Docker on Raspberry Pi - seems to start but can't connect

**Comment by alex-Arc** [comment]
hey @Punkerschaf  and @juzz197 
Thanks for the quick catch

Turns out one of our dependencies doesn't work with strict mode when build [node-osc](https://github.com/MylesBorins/node-osc/issues/112)

A new build should be up soon [v3.3.2](https://github.com/cpvalente/ontime/releases/tag/v3.3.2) if you could give that a try that would be great

**Comment by juzz197** [comment]
Got 3.3.2 in docker - all starting ok now!  Thanks for the quick patch!

**Comment by Punkerschaf** [comment]
3.3.2 works fine here also. Thanks @alex-Arc
