### ISSUE TITLE
Dockerhub "latest" includes alpha release

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime#1107]
I'm not sure what the process is that gets new GitHub releases up to dockerhub, but would suggest setting tags so that `latest` points to the newest production release, not (as is currently the case) the alpha build

**Comment by cpvalente** [comment]
> I'm not sure what the process is that gets new GitHub releases up to dockerhub, but would suggest setting tags so that `latest` points to the newest production release, not (as is currently the case) the alpha build

The docker release used to be maintained by a developer that is no longer collaborating with ontime.
He was of the opinion that the latest tag should (not exist or) contain the latest pipeline that ran, regardless of the release status.

I think that we should follow the principle of least surprise here and have otherwise no strong opinions.

If someone would like to come up with a tag plan that makes it easy to consume Ontime I am happy to add it to our plans 

@alex-Arc @lukestein what do you think?

**Comment by alex-Arc** [comment]
I don't know what is possible to setup.
But sice ':latest' is used if the user dose not specify anything it sould probably point to latest stable release 

And it would then be ok that, if you what a alpha or beta you can go and find the specific tag

**Comment by lukestein** [comment]
> But sice ':latest' is used if the user dose not specify anything it sould probably point to latest stable release 

This is definitely what is recommend, too

**Comment by cpvalente** [comment]
> > But sice ':latest' is used if the user dose not specify anything it sould probably point to latest stable release 
> 
> This is definitely what is recommend, too

Thank you.

From a quick look into the GitHub action, it seems that the intention is that we have two tags `latest` and `nightly` 

https://github.com/cpvalente/ontime/blob/master/.github/workflows/build_docker.yml

This makes sense to me. We likely just need to investigate why is the alpha release ending up in the `latest` tag since it is correctly tagged as a pre-release
