### ISSUE TITLE
Play sound when timer ends

### ISSUE THREAD

**Issue by nerif-tafu** [cpvalente/ontime#1109]
Hi

I was wondering if the ability to play a sound when a timer ends is planned at all?
Example here: https://stagetimer.io/blog/guide-timer-with-sound-alerts/

Thanks!

**Comment by cpvalente** [comment]
Hi @nerif-tafu, thank you for reaching out.

This has been brought up a few times. From my perspective, this is not something that we want in Ontime.

If there would be a user proposed implementation that is lightweight and detachable we could consider it. 
An eventual proposal that affects the demo page is more likely to be accepted since it has no impact on the remaining of the app.
Adding this should also be pretty trivial

Will close this ticket as we already have a standing ticket with this request in #1034
