### ISSUE TITLE
Display version in help menu

### ISSUE THREAD

**Issue by epnlespieux** [cpvalente/ontime#1154]
Hi,

Could you add the version of the running ontime software in the help menu or somewhere else easily visible ?

As your very good software is often updated, it will be cool !

Cheers

**Comment by cpvalente** [comment]
> Hi,
> 
> 
> 
> Could you add the version of the running ontime software in the help menu or somewhere else easily visible ?
> 
> 
> 
> As your very good software is often updated, it will be cool !
> 
> 
> 
> Cheers

Hi, thank you for your suggestion. The app version is currently in the settings. Do you think this is hard to find?

If we were to copy the version into the menu, there wouldn't be a button for you to check for updates, I am unsure on whether knowing the version on its own is a good improvement since you would still need to open GitHub to check the latest version

What do you think?

**Comment by epnlespieux** [comment]
![image](https://github.com/user-attachments/assets/d1db21bf-e237-4005-a7b4-545cd9ea830a)

No it's not hard to find once you know it's there :-). But even without a button to check for updates in the help menu, it can be faster to see.

Cheers

**Comment by epnlespieux** [comment]
![image](https://github.com/user-attachments/assets/dd1e183d-9663-481d-a41a-612cf74a7bab)

**Comment by epnlespieux** [comment]
> Meanwhile, are there any other items in these menus which you would propose improvements to?

you said it's not possible but a line to tell us "a new version is available" is there is a newer version.
But we can easily click on "See on github".
Thanks for your work 

ps : do you know the french bd author Lewis Trondheim ? His artist name comes from your town name (https://www.instagram.com/lewistrondheim/) ?

**Comment by alex-Arc** [comment]
@epnlespieux you can look forward to it in the next release
