### ISSUE TITLE
Custom templates for lower thirds (or documentation if possible already)

### ISSUE THREAD

**Issue by rob-fi** [cpvalente/ontime#1250]
The lower third feature is a nice addition, but it would be even more useful if there was a way to select between user defined HTML/CSS templates. Per event would be great, but at least globally. I note you can change some basic options in the lower thirds screen, such as colours or the in/out delay, but further customisation would make the feature far more useful for running events that have a particular branding/look.

It may be that at this point using the Custom Views (https://docs.getontime.no/features/custom-views/) feature is one way? Only thing is, I'm not sure if it's possible to reference the custom fields. Perhaps some documentation update required if so.

Thanks!

**Comment by cpvalente** [comment]
Hi @rob-fi , thank you for taking the time to make this suggestion.

I agree with you that we need better documentation around custom views. In general, this becomes challenging since there are so many cases that users bring forwards.

I suggest that we can create a small archive or quick examples. Ideally those would be user initiated.
Perhaps you would be available to create the lower thirds you need?

As for the question:
In earlier versions of Ontime we had more customisation and the concept of presets for lower thirds.
We since have realigned to have a single, simple example. Our position is that the lower third problem is well solved by other applications and we recommend we leverage one of those

As you mention, making your own is a possibility. There are plenty of lower third HTML / CSS templates out there

**Comment by rob-fi** [comment]
Thanks for taking the time to reply @cpvalente. Yes, I already use vMix for example to provide lower thirds, but I liked the idea for some types of productions having everything simply in ontime.

I can look into creating an example template, it's something that I'd essentially be doing when trying out the custom views anyway.

I opened another issue regarding documentation for the HTTP integrations, but this has some crossover for this issue, as during that process I discovered that I should be using eventNow.custom.mycustomfield, I presume it would be the same for the custom views.

**Comment by alex-Arc** [comment]
@rob-fi 
have you seen this example?
[Control Ontime from vMix](https://docs.getontime.no/quick-tips/integrate-with-vmix/#control-ontime-from-vmix)

**Comment by rob-fi** [comment]
> @rob-fi have you seen this example? [Control Ontime from vMix](https://docs.getontime.no/quick-tips/integrate-with-vmix/#control-ontime-from-vmix)

Hi, yes as I mentioned I'm already using vMix. No issues with integrating with that, but I don't always want to or can use vMix for everything, sometimes a browser source than can be put into whatever (be it vMix, OBS, Caspar CG and so on) to provide simple lower thirds would be handy, hence my interest in the feature.

**Comment by cpvalente** [comment]
Hi @rob-fi , I am not sure I see action points for us here. Would it be OK for us to close this ticket?
