### ISSUE TITLE
Move flip option to settings

### ISSUE THREAD

**Issue by RasterboxOff** [cpvalente/ontime#1253]
The option to flip a view is ideal for prompter situations, but the placing of the option should be within the view settings and not in the navigation bar.

**Comment by cpvalente** [comment]
Thank you @RasterboxOff 

Once you flip the screen, the settings is applied to all future navigations as long as you are in a signage view (production views cannot be flipped)

Moving this to the view settings would indicate imply that the setting only applies to the current view

I believe the correct behaviour is to 
a) keep the option where it is since it is an app setting. We would need to somehow indicate which views are flipped (or let the user figure it out)
b) move the option to the view settings, and make it apply to a single view only

What do you think?

**Comment by cpvalente** [comment]
Closing this ticket as we dont seem to have a clear actionable task.

You are welcome to re-open if we can provide a clear feature description that answers the points above
