### ISSUE TITLE
NDI / UltraStudio Support

### ISSUE THREAD

**Issue by hadphild** [cpvalente/ontime#1290]
NDI / UltraStudio Support.

Having all the views output onto NDI or assigning to full-screen view to and SDI or on of the displays attached.

**Comment by alex-Arc** [comment]
Hey @hadphild 
This is very unlikely to happen 
I would recommend that you look into something like [vingester](https://vingester.app/) or [obs](https://obsproject.com/)
(there are plenty of others)

**Comment by hadphild** [comment]
Was just an idea.

**Comment by cpvalente** [comment]
Hi @hadphild , as mentioned by Alex, we currently do not see this as a direction or a priority for Ontime.

There are plenty of tools out there that can solve this. However, I acknowledge the desire to reduce the amount of tooling you need in your production

I am sorry if this is not the outcode you hoped for, and I hope it doesnt discourage you from future suggestions

I will close the ticket for now since this is not planned in the near roadmap
