### ISSUE TITLE
Color bar - countdown time & tables view enhancement

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#130]
Hi
Would it be possible to have a colour bar count down timer - Green Amber Red.   Ideally under the timer displays in UI, back stage and tables views.

For the Table, we would like the green highlight bar to have a different behaviour than current.  Respecting the Green-Amber-Red countdown bar running on the current cue - the highlight bar moves to the next cue event as soon as the current event timer starts.  I think a different highlight color other than green should be used

For example, cue 3 is the current cue and has a Green-Amber-Red bar showing this cue timer is running
and cue 4 is highlighted as the next cue.  Similar to the markup logic applied to the studio clock.

<img width="712" alt="Screenshot 2022-05-22 at 8 48 07 AM" src="https://user-images.githubusercontent.com/29515324/169673752-59d649a1-2a6c-4b1b-9226-952a0f5f455d.png">

**Comment by cpvalente** [comment]
Hi @je71175, thank you for your help again.
This is certainly a good improvement, I will create a list of tasks related to cuesheet improvement and add it to the roadmap

**Comment by cpvalente** [comment]
@je71175. Just looking for some clarification on the colours here

If I understand correctly
- The current event (now in green) should change colour depending on the progress (green - amber - red)
- The event next gets highlighted in some colour. 

Do you have any opinions on the colour schemes here?

**Comment by je71175** [comment]
Have seen with other times,  the count down bar colors move between Green, Amber, Red.  The countdown bar in the Timer screen works nicely, and adding a color to visually highlight the end is approaching was really what I was imagining here. 
I suppose highlight the next cue in green (could be from a color picker?) works - as the cells in the row are highlighted as is the current behaviour.  The ask here was for the highlighed cue to tbe the Next cue (not the currently running one)
thanks

**Comment by cpvalente** [comment]
a-ha, I understand now. Thank you for the clarifications

The hightlight portion of the request I can probably sneak in the near future. Meaningful changes to the table component would have to follow #133 since there are several third party upgrades pending for continuing development in the table

**Comment by tcconway** [comment]
Following.

I'm a big fan of having the following color scheme (both in the editor interface and the cuesheet interface):

**Background color:**
- RED: Currently running event
- AMBER: The next running event
- The BLOCK "event" being transparent, bold, much bigger, padding above it and left-aligned.
- All others: Follow whatever the editor chooses when they set up each event

I've been able to set most of this using a browser plugin that alters the CSS, and it works great for me. Sadly since it's local-only, others can't see this color scheme.

**Comment by cpvalente** [comment]
Hi @tcconway , I like the sketches you have offered here and am incorporating much of this feedback in the new cuesheet design.
Few clarifications from my side:

What is the visual distinction between a playback colour (red, amber) and the user-selected colour? 
Perhaps the user colour should be contained in a cell rather than becoming the background of the row?
