### ISSUE TITLE
Feature Request: Sync with Google Sheets

### ISSUE THREAD

**Issue by Fred-DTV** [cpvalente/ontime#194]
Hi @cpvalente 

Thanks for this amazing project. It is truly a game changer.

I was wondering if it would be possible to have ontime linked to a rundown in Google Sheets, as were are mostly using Sheets because of the easy collaboration with others.

A simple import button would be enough for the beginning, and a real-time Sync would be the dream scenario

**Comment by cpvalente** [comment]
Hi @DachsbauTV , thank you for your suggestion. This really sounds like a good addition to the feature set.

Currently you can import any XLS file and we have a feature in testing to export CSV. This should provide good foundations to start a feature similarly to what you describe.

I am happy to write a feature description and it would be great to get some help. A few questions:
- Would this feature be targeted specifically at Google Sheets instead of a local instance of Excel? 
- Usually ontime would be in local / offline environments, is it a good idea to lock workflows into a cloud service?
- You would need to add account secrets to ontime which could potentially become a security risk, where would this information reside? I imagine it would be a file that can be added to the ontime installation?
- In what part of production would live sync be in place? There would be a risk for misuse and accidentally resetting the timers if used in live production. Could you give an example of your desired workflow?

Meanwhile it would be great if you could test the existing import, this should work fine with Google Sheets. Roundtrip import-export should be ready as soon as cb1da0b834a7c850b368f8fba1634db4082fc7d4 is merged. This is currently being tested and should be merged in the upcoming weeks. 
If you would like to get involved with testing it would also be very useful, drop me an email at mail@getontime.no and we can look through it.

Thank you again

**Comment by DachsbauTV** [comment]
Hi Carlos,

The current import works quite well with a downloaded .xlsx file from google sheets. (just the little hiccup with the user fields)
Why I think a Sheet implementation would be great is because in a bigger production environment where multiple people work on one rundown, it can be almost impossible to get a "final" file for download and import except just a couple of minutes before the actual live starts. Having to import the import the file at that point is a potential stress factor or even worse.

> * Would this feature be targeted specifically at Google Sheets instead of a local instance of Excel?
Yes, however there is an Excel Online which could use the same functionality. But I think, Sheets is still more common.

> * Usually ontime would be in local / offline environments, is it a good idea to lock workflows into a cloud service?
I think it is no problem, because almost all workflows in a production nowadays are online. And it still would only need a tiny bit of ressources (CPU/bandwidth/etc) which is no problem at that level.

> * You would need to add account secrets to ontime which could potentially become a security risk, where would this information reside? I imagine it would be a file that can be added to the ontime installation?
I think the Google Sheets API is encrypted anyways, but I am not experienced enough in this field.
Maybe take a look at https://github.com/bitfocus/companion-module-google-sheets how this is implemented. (However, be aware that it currently doesn't work haha) 
The workflow here is, to create a google Cloud app which creates an OAuth code specifically for that instance.

> * In what part of production would live sync be in place? There would be a risk for misuse and accidentally resetting the timers if used in live production. Could you give an example of your desired workflow?
Live sync could be a simple Cloud button for "sync on/off" which can be turned off during the actual live situation. 
There might be some shows, where a live sync during the On-Air is still wanted though and for these a live sync of ontime would be actually mindblowing :)

**Comment by progressmedia** [comment]
+1 for this feature! Please continue to try to work on it @cpvalente and thank you for all of your hard work to date on this.

**Comment by progressmedia** [comment]
Another point I wanted to mention to Carlos as well as anyone else wondering about this, one huge benefit to being able to do this, is to sync other similar services across platforms. So essentially your live data would 'live' in the Google sheets, which would then have specific columns for OnTime to read, and in my specific case, would also have columns for Rundown Creator to read, so that the net effect is a sync'd up timer and scripts between Google Sheets, Rundown Creator and OnTime. That's not really feasibly possible ATM having to set up some kind of python script to automatically run everytime a google drive change is made, and then importing that excel sheet to ontime routinely.

**Comment by cpvalente** [comment]
Hi @progressmedia , thank you for sharing your thoughts and for your feedback.

I believe is a great feature for ontime but we do have some concerns, which I have outlined previously.

However, your second comment does give me an idea

> That's not really feasibly possible ATM having to set up some kind of python script to automatically run everytime a google drive change is made, and then importing that excel sheet to ontime routinely.

This would be a great way to prototype the flow. We create an external service (script) that syncs ontime and google sheets. If this proves to work well we will have, by then, a mature proof of concept to implement in ontime.

If you can create a repo with the Google sheets part, I am happy to help with making the script synchronise to ontime.
We could begin with downsync Google Sheets -> Ontime to begin with
What do you think?

**Comment by progressmedia** [comment]
Thank you for your response. I wish I could be directly more help, but I don't know any programming languages and the Python mention was just a passing thought. That being said, would something like this be a good starting place? Do you think this could work? https://youtu.be/8asKP-rssx0

**Comment by alex-Arc** [comment]
Hey @Fred-DTV @progressmedia @hrueger
would you like to give this a try?
https://github.com/cpvalente/ontime/releases/tag/v2.22.0-sheet-beta.1

you will need to create a OAuth 2.0 Client ID in console.cloud.google.com
Select `Web Application` as the Application Type
And in `Authorised redirect URIs` add `http://localhost`
Then create and download the client secret and upload it to ontime

**Comment by alex-Arc** [comment]
@hrueger Good catch, I was testing from the cli so did not notice the electron behavior
the client.json was not being saved properly, that is also fixed now
https://github.com/cpvalente/ontime/releases/tag/v2.22.0-sheet-beta.2

**Comment by Fred-DTV** [comment]
This is so amazing that you've added this

I am really sorry that I couldn't help with testing, we have been moving office and there was just no time for me.

Really looking forward to use this feature in the future
