### ISSUE TITLE
Bug: Import overwrites user fields

### ISSUE THREAD

**Issue by DachsbauTV** [cpvalente/ontime#195]
Hello,

I found a little bug: When importing an excel spreadsheet, the pre-defined user fields would get deleted.
So with every import (basically every update of a spreadsheet) it is necesseray to fill out the user fields again.

**Comment by cpvalente** [comment]
Hi @DachsbauTV , thank you for the report.

This happens because the importer looks for labels in the user fields such as `user0:fieldName` as described [in the docs](https://cpvalente.gitbook.io/ontime/features/import-events-from-excel)

This is indeed counter productive behaviour and should be revised. I will add a patch to production

**Comment by cpvalente** [comment]
Thank you @griffon56. Great that you took the time to get involved and help with issue tracking.
I will prioritise a fix for next release (lately I have been releasing once a month).

It is also a good idea to add the remaining fields as you mention. Currently there is a feature in testing to export CSV. It would make sense to do this changes after so that I can keep a round trip import / export in sync.

Meanwhile I was unable to recreate the issue with isPublic.
What system are you using? Are you doing this through the app or browser? Do the other fields work fine?
It seems that the app can recognise any text in the a field named 'is public? (x)' 'is public' or 'public' as a positive. Can you share some screenshots of your imports? Even better would be the failing excel file, you can send it to mail@getontime.no

**Comment by cpvalente** [comment]
Hi @DachsbauTV , I am actually unable to replicate this.

I create an excel file with some named user fields (eg: user3:test3) and some undefined (user0)
When importing the above, user0 maintains whatever was set before.
Can you please show me a sample of what you are using?

I do however manage to replicat ethe bug reported by @griffon56 and this will be fixed
