### ISSUE TITLE
Roll mode fails when time repeats in 12h time

### ISSUE THREAD

**Issue by MilkMGN** [cpvalente/ontime#238]
Title says all, when you start roll mode at say 11pm and you have an hour of cues it wont start till 12am, opting to start a one housr timer.  Maybe i am doing something wrong, as i would really like to use 12h time instead of 24h

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/42798255/199494346-4fcd355b-7607-43cb-b556-a9ff2180e366.png">

**Comment by MilkMGN** [comment]
Sorry, forgot to demonstrate time.
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/42798255/199495099-44243711-21d1-4e58-b8db-5968877fd27b.png">

**Comment by MilkMGN** [comment]
Okay, I've figured it out. Those start and end times are actual times. Is there a way to make them be untied? Just when you press start roll mode it goes from then? Or would i have to make a JSON file for every show time? This is something i need to use ASAP for a show we start runthroughs of on Saturday.

**Comment by MilkMGN** [comment]
What i was expecting ontime to do is start the timer when i press Roll Mode. So instead of 00:00:00 being 12am, 00:00:00 is when the Roll mode button was pressed.

 Maybe i’ll just make 5 different json files with the show times set

**Comment by MilkMGN** [comment]
Hey, this has been marked as completed but the latest commits do not mention this issue. What do i need to do to make this work?

**Comment by cpvalente** [comment]
Hi @MilkMGN, 
In short: this issue was closed because I dont see a course of action here. 

It seems to me that there is a misunderstanding to what Roll mode is. Roll mode allows the app to run all events in an automated mode using your system clock.
The workflow you expect does not exist in ontime.

I do believe it would be a great addition and will make sure it becomes part of the roadmap when the time is right. For now we have #116 as a placeholder. You are welcome to contribute with ideas on how it could work on another issue or open a new issue with a description of a feature request

Hope this helps clarify
