### ISSUE TITLE
Ontime logo (aka menu button)

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#245]
I'd like to suggest a feature for the Ontime logo/menu button that shows at the top-right of various web views.

Make the menu/logo completely invisible. EXCEPT...
- If the mouse moves over any part of the web page in any way, it shows up.
- Auto-hide, after so many seconds.
- Make the logo look more like a button. Perhaps use the rectangle with the three lines in it?
- Put it top-left of the screen
- Maybe even do a gradient background overlay over 1/5th or so of the left part of the screen

This would be extremely useful to use these in production/onair as we wouldn't have to crop out that portion of the screens.

For branding, I'd just simply put "Powered by Ontime" in subtle text at the bottom of the screen.

Here's an example: https://ibb.co/RT7RVRS

**Comment by cpvalente** [comment]
Hi @tcconway, this makes sense to me and I dont have any objections to the change .
Ontime is a free, opensource software which does not generate any money, branding is not a priority.

Thank you again for the suggestion and the sketch. It is very helpful.

**Comment by tcconway** [comment]
Thanks @cpvalente. Here's some updated images, for your consideration.
https://ibb.co/album/TqFWYS

**Comment by je71175** [comment]
I think this is a nice idea actually.  I can see the use case where these screens are used to generate content for a downstream workflow (rather than being the end-user display directly)
We use these content screens on tablets and raspberryPi for end user content.  For tablets its direct user interaction, for Pi, we VNC into the device for Remote Desktop from a central pc. 
For the /minimal?hidenav=true parameter, i think works well also as long as it could be triggered from a Remote Desktop / tablet, ie, non-keyboard to type in the URL.
Thanks!

**Comment by tcconway** [comment]
Right now, we use these web pages two ways-
- bring in a web page as an input in vMix, Resolume or Millumin. Then we route it to downstage monitors, speaker monitors etc. wherever we need it
- The other way we use this is to put a Mac mini or Pi with a monitor and just have it run independently as an onset monitor or a client monitor.

As for hiding the logo/button, although the url variable can work, I do love the “hidden by default, but shown on mouse movement”. Seems more elegant.

**Comment by cpvalente** [comment]
sounds good to me, I will be in touch for some feedback

**Comment by cpvalente** [comment]
Some in v2
