### ISSUE TITLE
ALT hotkey combinations on Mac doesn't work to create new Events, Delays, or Blocks.

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#247]
Pressing the ALT+E, ALT+D, or ALT+B keys on a Mac doesn't add an Event, Delay or Block.
Even as you probably know there is no "ALT" key labeled on Mac keyboards...Option can fill in here...but doesn't seem to work.

It would be nice to have this shortcut be Command-E, Command D, or Command B too since there technically isn't a key labeled "ALT".

**Comment by cpvalente** [comment]
Hi @tcconway.
The challenge with the shortcuts here is that a large portion of ontime users use the web version of the app in the /editor route

Actually, from the beggining this is the preferred way to use the app and is something I would like to support. In this case the use of Command becomes problematic since it collides with browser and OS shortcuts, hence the Alt key.

However, I was not aware that the shortcuts are not operational in MacOS and it seems that is should be an easy enough fix.
I will make sure this gets added on v2 if not earlier
