### ISSUE TITLE
Minimal View

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#279]
It looks like the "Minimal Timer" doesn't adhere to the End Message text. It only counts in the negative.

Steps to repeat:

1. Put some text in "End Message" in Settings.
2. Run a timer, allowing it to go past 0
3. Notice that the End Message shows up in the default timer display and not the "Minimal View" display, which shows it counting in the negative.

Thanks.

**Comment by cpvalente** [comment]
Hi @tcconway 
<Minimal Timer> attempts to not be opinionated on how it runs.

From the users I have contact with, it is often used in production rather than on a stage / speaker environment.
Hence the smaller feature set.

A way forward would be to allow the configuration of the view, perhaps a URL parameter that could enable the end message.
Something like `http://localhost:4001/minimal?showEndMessage=true`

There is also an argument that the current default view <Stage/Presenter Timer> is too opinionated and users might prefer the <Minimal Timer> as a speaker timer. In which case we should be looking at a different set of solutions

What do you think?
What is your use case for <Minimal Timer>?

**Comment by tcconway** [comment]
Looks amazing in v2
