### ISSUE TITLE
Pip view, add iframe or embaded www option

### ISSUE THREAD

**Issue by eustachy84** [cpvalente/ontime#281]
Hello

I want to use PIP option with combination vdo.ninja. I'm serching for simpler (and more efficient) way, that I will run obs, to overley PiP webpage with vdo, send stream and konwert to webpage to show on backstage.

**Comment by cpvalente** [comment]
Hi @eustachy84, thanks for reaching out.

It shouldn't be particularly complex to embeds a video stream on a browser. However, I am not aware of any software solution for this. My workflows (and there workflow around which ontime was designed) used d3 for this particular scenario.

Having said that, since on time is not able to provide a complete workflow for PiP, this view is being considered for removal as part of v2
