### ISSUE TITLE
request: CLIP Remaining time from Millumin

### ISSUE THREAD

**Issue by sledzik1984** [cpvalente/ontime#318]
I would be great to have clip remaining timer that is actually playing (like in Clock-8001)

Millumin is sending that via OSC. Ontime should allow to choose from which layer to get time from.

That time should be available only on non public screens (like backstage or studio)

**Comment by cpvalente** [comment]
Hi @mmattausch 

Thank you for reaching out.
I am skeptic of creating specific integrations to other software, but have however no objections in creating an open endpoint to set this (which you can configure something else to populate)

The only point standing is that I am unsure on how best to fit this in the current designs
Could you please checkout the most recent release (v2 beta 2 as of now) and provide a suggestion?

https://github.com/cpvalente/ontime/releases

Feel also free to get in touch on mail@getontime.no

**Comment by Keksstar** [comment]
#115 is also part of this request.

Don't open it up for specific software, just provide an entry point for OSC time data.
Everything before (between specific software and ontime) can be solved by middleware.

**Comment by cpvalente** [comment]
Agreed. The server is ready to receive this data and I will implement as soon as I can get some help defining which screens should present this and where should it go

**Comment by Keksstar** [comment]
Should be shown in the event itself... if you have it there, it will be reflected to all other views?

**Comment by cpvalente** [comment]
Hi @Keksstar ,

There are a few challenges here.
As much as ontime can receive a string from another software, it would not understand what to do with it, and its value is purely presentational.

I would be inclined to believe this piece of data should be completely detached from Ontime so as to not have negative consequences to users who do not follow this workflow.

I would suggest Ontime can display this string in the **Info tab** in the Editor or perhaps in the **message control** section (where onAir is)
When it comes to the views (backstage and studio clock as mentioned here), we would need to find a place for it to be shown that follows the same principles. A user that does not follow this workflow should not see an empty section or the UI should not feel incomplete.

If we could gather some suggestions on this presentations. The remaining work is ready

**Comment by mmattausch** [comment]
I use the remaining time display mainly for the preview monitors on stages (for hosts or speakers) and in FOH for all other operators (lighting, sound ...). 
Usually the time for a whole slot runs in the timer - e.g. 20min interview, and this slot is interrupted by a short clip whose timing is announced by the presenter. That's why I find the function of my timer so useful to display both times in parallel, as long as the clip is running, in order to allow the people on stage a clean re-entry into the programme.
This would be a fantastic feature in ontime, as I could then eliminate the need for the second timer where ontime is shown. 

Translated with www.DeepL.com/Translator (free version)

**Comment by cpvalente** [comment]
Hi @Keksstar and @mmattausch , suggestion from my side:

In the original designs of ontime, the message was a field under the clock.
The engineers we collaborated with at the time, thought it was not bringing enough attention to the message, so we opted for the fullscreen overlay we have today.

What would you think of a solution that would include:
- the message overlay goes under the clock, a small variation of the design attached
- the message overlay can be set over OSC

This means: no more fullscreen cover, and the message field in the editor is the same as the API. it will be up to the user to manage this usage

As to the design relic of ontime prototype...

![original overlay](https://user-images.githubusercontent.com/34649812/233477594-8a9c9dc7-2eeb-4e7c-9e4d-ef614d49c5bc.jpg)

**Comment by Keksstar** [comment]
Wondering where were at with this, after a a while? Is there anything implemented already?

**Comment by cpvalente** [comment]
Hi @Keksstar , great to see you involved.
This ticket hasn't got any attention since we haven't received users feedback on this.
To me that signifies that there is little demand for this feature and our work is best suited elsewhere.


It looks to me that the major effort in this feature is in the design clarification. Perhaps if you are able to help by replying some of the questions above we are able to implement in a near release
