### ISSUE TITLE
Cuesheet CSS suggestion

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#365]
Hi there.
Would love to suggest this CSS style for the /cuesheet. Note: the blue bar was set in the editor.

Would also like to bring in the "Started at" and "Finish at" times if possible. Those are super useful.

Note too the Break row with a black background, larger font, and padding-top to really help this stand out.

Maybe also a thick red border around the active cue (not just the green background)

![Suggested Color Scheme + Layout](https://user-images.githubusercontent.com/403326/234984730-6137a028-fdbc-4228-9b86-b164f5389b70.jpg)

**Comment by tcconway** [comment]
Here's another shot of the CSS I use for the /stylesheet. Note: I'm using Stylebot to adjust these colors/layouts in my local browser only.

Of note:
- I made the Block be black-background, larger font, and aligned-left
- The red bar is the currently-running event.
- The gray box is just the hover-over color. Unsure why a hover is need, imho.
- All the others are color coded within Ontime.
<img width="1720" alt="Screenshot 2023-04-29 at 9 21 17 AM" src="https://user-images.githubusercontent.com/403326/235312952-b43e9dd3-8467-4ea8-9249-bd8101316fa2.png">

**Comment by cpvalente** [comment]
Hi @tcconway , great work as usual
I am working on a revision to the cuesheet, mostly technical, but a good opportunity to revisit the styles

![rundown](https://github.com/cpvalente/ontime/assets/34649812/3c0b5432-d813-4c2b-8abe-67ec7e78badd)

I wonder about a few details, hopefully you can help:
- Should the start and end time of a delayed event be orange?
- Should the delay chevron be inline with start and end time or should it be its own cell?
- I have currently not applied any highlight to the "next event", since I believe the red does a good enough job at it. What do you think?

**Comment by je71175** [comment]
To add a feature request on cuesheets, I would like the option to hide past events as in our workflow, we would never go back and look at a cue that has already passed

**Comment by cpvalente** [comment]
We took a lot of this and implemented with #435 , thank you @tcconway and @je71175
