### ISSUE TITLE
Event is public + Start time is last end not being saved.

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#368]
Version: 2.0.0-beta5

Can't make event private, nor change the start time is last...

Steps to Repeat: 
- Select an event
- Un-tick "Event is public" and/or "Start time is last end"
- Click on another event then click back to the originally selected event.
- The tickmarks didn't save and will show ticked.

**Comment by cpvalente** [comment]
Hi @tcconway. Thank you again for your feedback

Let me see if I understand.
you have 2 events in the rundown:
- click on the first event, revealing the quick add buttons
- make a selection (eg: not public + start is last end)
- click on the second event. The first quick add will hide
- click back on the first event. Your options are gone

The settings here are supposed to help you create a new event with the current data. They aren't meant to be persisted.
If you want to persist these settings, you must do it in the App Settings.

With this in mind, This isn't a bug to the extent that it is the expected behaviour.
This also means that you should be able to make a selection here and click on the Event button to see your options applied. Is this the case? I wasn't able to replicate any issues

It could, however, be bad UX. 
I would be cautious about making changes here since we could introduce stale data and potential performance drawbacks

**Comment by tcconway** [comment]
I see now, thanks for the clarification.

It does look as if those two checkboxes are settings for the identified event. Definitely a UX thing to think about.

For consideration and discussion:
- The [+ Event] button at the top of the screen is taking up a lot of real estate. Remove it allowing more room for events.
- Have the [+ Event] button be within each event, possibly similar to and next to the existing two buttons at the top right of each event.
- Remove this bar altogether:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/403326/235315026-9ac4294d-1d8c-4bd4-ab5d-f297421cd854.png">
... and make it be a popover/slideout/other interface shown once a user presses the [+ Event] type button


Thanks again!

**Comment by cpvalente** [comment]
Thank you, lots of good input there. Few questions from my side:

> The [+ Event] button at the top of the screen is taking up a lot of real estate. Remove it allowing more room for events.

The + Event button is currently the only way to add an event at the top of the list or to delete all events. How would you suggest doing this instead?

> Have the [+ Event] button be within each event, possibly similar to and next to the existing two buttons at the top right of each event.

Perhaps I am misunderstanding, is this not what the ellipsis button does?

> Remove this bar altogether:

You can hide the bar in app settings. It is called "show quick entry on cursor". 
I believe hiding the bar is not optimal as it allows quickly adding several events and introducing users to a few event concepts and shortcuts. It is also a good place for future extensions
However, a good point might be to automate it so that it shows only in edit mode. What do you think?

**Comment by tcconway** [comment]
Thanks for your considerations here!

I see the [..] button now! *facepalm* I've only just used that to delete. *sigh* So embarrassing. 
What about having the [...] button be:

```
Add Event Beforre
Add Event After
---
Add Delay Before
Add Delay After
---
Add Block Before
Add Block After
--- 
Clone Event
Delete Event
```
or 
```
Add Before...
     Event
     Block
     Delay
---
Add After...
     Event
     Block
     Delay
---
Clone Event
Delete Event
```

This might be overkill, but it definitely allows you to lose that top + Event button.

Perhaps rename the setting from "Show quick entry on cursor" to "Show the Add a new Event shortcut entry bar under the currently selected event. -- No idea what that meant when I originally saw it. I'll definitely make use of that setting now I know what it does!

Another UX design approach for this shortcut entry bar (or whatever it's called) would be to have it more separated top-bottom from each event and add a label "Add a new Event" or whatever makes sense. Wondering if having this bar have an outline like the events have, or a different dark color background would make this more obvious that it's not part of the previous or next event?

**Comment by cpvalente** [comment]
This makes sense and is something we have discussed in the past

The rundown header is prime real estate for adding options related to the rundown in future.

One of the issues with v1 was that, on the fight to save screen space, we locked ourselves into being unable to add good UX. Several of the feedback we got was that Ontime was hard to figure out.

This is where my head is at on removing the bar:
- we would need to add noise to the subsequent menus to make sure everything is covered
- we would still need to find a way to affect the entire rundown (eg, delete all)
- we might be making it so that is harder for us to extend in future

I wonder if in the long run, the extra 90px are worth it.

**Comment by tcconway** [comment]
Thanks.

I wouldn't want you to lose that 90px space -- but rather  use it for top-level features like you are describing. Right now there's a lot of open space there and, like you, feel there is a lot of operational functionality that could go there ;-)

**Comment by cpvalente** [comment]
Hi @tcconway . Could this issue be closed?
If you have any thoughts on functionality which you would like to bring forwards to the top menu, please feel free to open another issue
