### ISSUE TITLE
keep several project files in user folder

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#374]
As a very future request, it would be great to enhance the setup and configuration in case a event runs more than 1 day.
Sometimes events get planed for 2-3-4 days and applications and organiser have to plan multiple days.

Maybe in the long future of Ontime, it would be possible to get tabs on the top of editor app.
Each tab could be a day of event and can be configured.

any consultation or feedback is highly welcome.
Thank you for your support!

**Comment by je71175** [comment]
Multiple days and multiple stages (eg a festival) or rooms (eg concert).

**Comment by cpvalente** [comment]
I appreciate this is probably not what you would like to hear:

Ontime has no concept of time in a schedule sense. All time is tracked in relationships between events in milliseconds.
We could modify the app to deal with real date objects, but I am sceptical whether this is the right direction for the app.

>  Each tab could be a day of event and can be configured.
What would this configuration look like? What things would be configurable in a per day basis?
Is day the right split for an event? Often an event is not constrained by a 24-hour period. Would this mean that an event and a day have to be two different concepts that would need to be fully implemented to realise this feature?

> Multiple days and multiple stages (eg a festival) or rooms (eg concert).
Extending this into a multi-room concept from a single ontime instance is a task for another app since it is such a fundamental re-write

However, I do like the idea of Ontime being able to hold onto multiple projects you could easily load. @iqtreiber and @je71175 would that be a correct step forwards for you?

**Comment by je71175** [comment]
Yes, I think that works fine.  thank you

**Comment by cpvalente** [comment]
Writing some feature requirements here

Currently, Ontime keeps a single json file with its definition.
The file is kept in a public folder resolved in [getAppDataPath](https://github.com/cpvalente/ontime/blob/master/apps/server/src/setup.ts#L11)
When a new file is loaded, we delete the existing and upload and parse the new

Nice...

### Feature requirements
We need ontime to keep several files in the public folder. This would mean a few things:
- We need somewhere to see a list of existing files. I would suggest that we use the <[UploadModal](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/modals/upload-modal/UploadModal.tsx)> and repurpose as a generic "load file modal"
- When we [upload a file](https://github.com/cpvalente/ontime/blob/master/apps/server/src/utils/upload.js), we make a temporary name. We would need to keep the user names

### Some pointers
This is mostly a nodejs issue.
We would need to get a list of the files in our public folder and create an endpoint to retrieve this and show in frontend.
We would then either a) send the path of the file we want to the currently existing upload endpoint, b) create a new endpoint which loads a file in the db directory c) your better idea

I believe we shouldn't need any other changes. When a file is loaded, it is parsed and corrected by ontime.

**Comment by arymoraes** [comment]
@cpvalente let me know if you want me to start on it, and which tasks should I work on

**Comment by cpvalente** [comment]
> @cpvalente let me know if you want me to start on it, and which tasks should I work on

Hi, can you make sure that the task is clear to you?
Once you understood what we are trying to achieve you are welcome to start with step 1 and 2. We can pit stop then to check implementation.

I will help you as needed towards the end and as needed. Is this ok?

**Comment by arymoraes** [comment]
> > @cpvalente let me know if you want me to start on it, and which tasks should I work on
> 
> Hi, can you make sure that the task is clear to you? Once you understood what we are trying to achieve you are welcome to start with step 1 and 2. We can pit stop then to check implementation.
> 
> I will help you as needed towards the end and as needed. Is this ok?

From a high level standpoint I understood the task, but I'll explore a bit of the code to make sure I understood it properly either today or tomorrow and will confirm.

**Comment by arymoraes** [comment]
@cpvalente yep it's what I thought, I'll start step 1+2 this week then, will let you know if I run into walls

**Comment by arymoraes** [comment]
@cpvalente I have a few questions here, mostly on these two points:

Currently, when [a file is uploaded](https://github.com/cpvalente/ontime/blob/master/apps/server/src/utils/upload.js), we name it as db.json, since we only ever have one file. We would need to change this behaviour to keep the original file name given by the user

Currently, when the app loads, we load the one db.json. we would need to add some logic to select what to load, or create a file if nothing exists

I only see the upload middleware being used in two routes: /ontime/db and /ontime/preview-spreadsheet. It uploads a file, do stuff with the data, and load it into the app and deletes the file, is there anywhere else we use the upload that I'm not seeing? 

If not then task 1 should be straightforward and I'd be close to finishing it. 

For task 2 the uploading multiple projects should be also a bit straightforward just two questions:

What if we upload files with the same name? Should behaviour be warn the user and overwrite? or rename the new upload?
We'd need to know the latest loaded file, I was planning on having this as a field on `db.json`

**Comment by cpvalente** [comment]
Hey, great questions here, it seems like you are on it

As far as relevant cases for uploading of project files, we have the ones you outlined
https://github.com/cpvalente/ontime/blob/master/apps/server/src/routes/ontimeRouter.ts#L41

As for uploading multiple files, we would need an endpoint that lists existing files in the directory and allow the user to choose an existing file as well as uploading a new one.
If the file has a name already in use, we ideally would like to warn the user, but as a first step, we can skip this if the cost of implementation is too high. In that case we can add something in the return message

the `db.json` is the project file users will be uploading. 
Is it your idea that we copy the data of the uploaded file to the db.json and continue using this as our persistence file?
Considering we add a field in the project file `lastProject: "userProjectFile.json"`, we cannot guarantee that the file still exists when we next load the app since it is expected that users share this file across instances of the app. 

I think this could work, alternatively we could use a similar process to the resumablity service to have some data about the runtime. From the top of my head, I cant see one variant being objectively better than another. What do you think?

**Comment by arymoraes** [comment]
> Hey, great questions here, it seems like you are on it
> 
> As far as relevant cases for uploading of project files, we have the ones you outlined https://github.com/cpvalente/ontime/blob/master/apps/server/src/routes/ontimeRouter.ts#L41
> 
> As for uploading multiple files, we would need an endpoint that lists existing files in the directory and allow the user to choose an existing file as well as uploading a new one. If the file has a name already in use, we ideally would like to warn the user, but as a first step, we can skip this if the cost of implementation is too high. In that case we can add something in the return message
> 
> the `db.json` is the project file users will be uploading. Is it your idea that we copy the data of the uploaded file to the db.json and continue using this as our persistence file? Considering we add a field in the project file `lastProject: "userProjectFile.json"`, we cannot guarantee that the file still exists when we next load the app since it is expected that users share this file across instances of the app.
> 
> I think this could work, alternatively we could use a similar process to the resumablity service to have some data about the runtime. From the top of my head, I cant see one variant being objectively better than another. What do you think?

Think it makes sense, what I thought is that we'd check for the file so `lastProject: "userProjectFile.json"`, and if it doesn't exist anymore we could try to get the one with the latest updated at date? (I'm not 100% sure on how to do that but I assume this is possible)

**Comment by cpvalente** [comment]
Sounds good, this also sounds like a detail that is easy to change later on if needed.

What is the flow you have in mind here? 
I tried outlining possible scenarios below. From what I can see as long as we have a db.json always available we should be able to cover all the use cases.

```
Scenario 1.a: User starts app and the project file exists
- Application looks for db.json (which always exists)
- Application looks for `lastProject` field
- Application tries to find the file from step above and imports / parse if available
- As a side effect of the parsing, the data of lastProject is now part of db.json

```
```
Scenario 1.b: User starts app and the project file does not exist
- Application looks for db.json (which always exists)
- Application looks for `lastProject` field, this could resolve to hasBeenDeleted.json
- Application tries to find the file from step above and does not find it
- The field lastProject is set to empty in db.json

```
```
Scenario 1.c: User starts app for first time
- Application looks for db.json (which always exists)
- Application looks for `lastProject` field, this should be empty now

```
```
Scenario 2: User uploads a project file
- Application has a loaded db.json
- Application uploads and parses a new project file userProjectFile2.json
- As a side effect of the above step, the contents of userProjectFile2.json are moved to db.json and a field lastProject is populated with the value userProjectFile2.json

```
```
Scenario 3: User selects a previously uploaded project file
- Application has a loaded db.json and a previousProjectFile.json in its directory
- User selects previousProjectFile.json 
- As a side effect of the above step, the contents of previousProjectFile.json are copied to db.json and the field lastProject is populated with the value previousProjectFile.json 
```


We would likely also want to add an option for the user to name the current project
```
Scenario 4: User wants to save the current project file
- Application has a loaded db.json that is currently loaded
- User uses the interface to save the current project file, named newProjectFile
- Application makes a copy of db.json as newProjectFile.json and populated the field lastProject in db.json to newProjectFile.json
```

What do you think?

**Comment by cpvalente** [comment]
Hi @arymoraes , any news here?

**Comment by arymoraes** [comment]
> Hi @arymoraes , any news here?

I have steps 1 and 2 (mostly) done, just thinking if theres a way to make it more correct, steps 3-5 should only take a few hours and I can finish step 2 and work on 3-5 during the weekend.

Also I need to write unit tests for steps 1-2

**Comment by cpvalente** [comment]
Nice, thank you @arymoraes
Would you mind opening a PR so that the process is more transparent? It also gives us a chance to make sure we are going in the right direction. It also gives us a place to talk outside the github issue, which is more in the domain of the users

If you prefer, we can work with stack PRs on the steps, or whatever you find convenient

Steps 1-2 should be mergeable without impacting the app

**Comment by cpvalente** [comment]
Completed in v3 with #684
