### ISSUE TITLE
Feat: Create context menu for <EventBlock> component

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#389]
We want to allow quick actions on events without opening the event editor.

The planned strategy is to have a custom context menu which appears when right-clicking the event.

Development tasks:
- Create a reusable event context menu component
- create logic to show menu when right-clicking on <EventBlock>
- show a single entry in the context menu which lists the clicked event ID

We will use this as a springboard to allow quick actions on selection and, eventually multiple selections.

**Comment by asharonbaltazar** [comment]
I'd love to help with this feature. Is it possible to assign it to me?
Appreciate it!

**Comment by cpvalente** [comment]
@asharonbaltazar done!
Let me know if you need some pointers

**Comment by asharonbaltazar** [comment]
Okay, just to confirm before I make any changes: 

On the `/editor` route, there's a list showing the events. A user can add an event, edit an existing event, and delete events. There are other functionalities as well. 

So _this_ event list item need to be right-clickable, and when doing so, a context menu shows up.

**Comment by cpvalente** [comment]
Hi @asharonbaltazar Really good that you ask for clarification.

I believe you have the right idea, but it doesn't hurt clarifying.

In the /editor route there is a list of events on the left `<Rundown>` component

This renders a bunch of different elements. The issue task is implementing the context menu in the `<EventBlock>` component.
Right-clicking anywhere here should open the custom menu as described
Rundown -> https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/rundown/Rundown.tsx
EventBlock -> https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/rundown/event-block/EventBlock.tsx

**Comment by asharonbaltazar** [comment]
Sounds good. Then we're on the same page 😄

**Comment by asharonbaltazar** [comment]
@cpvalente 
I've managed to implement the context menu. However, there are multiple ways we can approach this solution, so I'll lay out some options and you pick whichever will suit you best. Props-wise, it'll stay the same, but the apporach to tie the context menu to a child will differ:


#### Option 1:
```tsx
<ContextMenu options={[{ label: `Event ID: ${eventId}`, icon: IoPeople }]}>
 {(ref) => (
   <div ref={ref as RefOject<HtmlDivElement>} {/* props */}>
    {/* children */}
   </div>
 )}
</ContextMenu>
```
**Pros**: Ability to attach the context menu to a specified child. Negates the need for wrapper elements. 
**Cons**: Typescript limitation in typing the `ref`. It's a generic extending `RefObject<HtmlElement>`. Since the `ref` is missing certain element properties, this approach errors out when attaching to a `HtmlDivElement`. Solution is to cast the `ref` to whichever `Html(type)Element` we need 

#### Option 2:
```tsx
<ContextMenu options={[{ label: `Event ID: ${eventId}`, icon: IoPeople }]}>
 {/* children */}
</ContextMenu>
```
**Pros**: Wrapping `children` with a component looks (arguably) cleaner. We don't have the `ref` casting issue of the first approach.
```tsx
<>
  <div ref={contextMenuRef} style={{ display: 'contents' }}>
   {children}
  </div>
  {isOpen && ( /* ContextMenu logic goes here */ )
</>
```
**Cons**: This approach necessitates a wrapper `div` (or whatever other element) in `ContextMenu`, and unlike the first approach, introduces the need for unneeded elements. Styling might be slightly more contrived due to the extra element. 

#### Option 3:
```tsx
<ContextMenu 
 options={[{ label: `Event ID: ${eventId}`, icon: IoPeople }]}
 as="div" // <-- specify any element here, ala HeadlessUI style
 {/* div props */}
>
 {/* children */}
</ContextMenu>
```
**Pros**: Doesn't have the cons of option 1 or option 2. Relatively flexible and clean. 
**Cons**: Will take more time to implement. I haven't studied ChakraUI's component offerings too closely, but perhaps there's an element we can extend to serve as a "base" for this ContextMenu component. I can also picture running into some typing trouble when attaching a `ref`.

Lemme know what you think. Perhaps you have better ideas!

**Comment by cpvalente** [comment]
Hi @asharonbaltazar , great work here!

I am generally against trying to predict the future and prefer the simplest implementation that makes it work now.

However, there are a few things we know we want
- Possibility to style a context menu entry
- Context menu entries should have callbacks attached to their onClick

With this in mind: I don't see that any of the outlined options is objectively better. You probably have investigated this longer than I have, so I will trust your judgement. 
If I was developing this, I would be inclined towards the second option as it seems to be the easiest to implement and I don't see any immediate issues. We can always refactor if needed

Few pointers:
- I like how you kept your implementation close to the browser context menu. good stuff
- We can leverage the chakra UI menu component to build the actual menu
- Could we do anything to prevent having to preload this component when the parent component mounts? Some crazy folks out there are using ontime with nearly 1000 events...
- Typescript is supposed to help us. If it gives trouble in something that doesn't spread consequences through the app, I am cool with slapping a `@ts-expect-error` on it

I realise this is a long non-answer, but I hope it is still helpful. Otherwise, please feel free to continue the conversation

**Comment by asharonbaltazar** [comment]
> Could we do anything to prevent having to preload this component when the parent component mounts? Some crazy folks out there are using ontime with nearly 1000 events...

Maybe we can write a `ContextMenuContext` component that'll create a single context menu for the entire app. And using the power of closures, it'll be possible to pass options arguments to the event handler function. I'm thinking of maybe calling it in the event like so:

```tsx
const openEventContextMenu = useContextMenu( /* context menu options here */ ) 

return ( 
 <div onContextMenu={openEventContextMenu}>
 </div>
)
```

**Comment by asharonbaltazar** [comment]
This approach is cleaner – I like it. I haven't tried it and might run into some issues, but it seems possible on paper.

**Comment by cpvalente** [comment]
Looks very clean. good stuff

Remember that for now we know what are the boundaries of the element since it will only be used in <RuntimeEntry> components. No need to generalise too much

Also, nevermind my comment on leveraging chakra UI menu. the performance is not great
