### ISSUE TITLE
Use dark UI for settings when dark mode in OS is detected

### ISSUE THREAD

**Issue by 12xx12** [cpvalente/ontime#421]
Tested OS: Win10
Ontime Version: v1.10.2

Example Image
![ksnip_20230531-212602](https://github.com/cpvalente/ontime/assets/44411062/8e327101-9bef-4acb-a67b-a7065a1d7723)

**Comment by cpvalente** [comment]
Hi @12xx12 , this is a good observation.

To give some context:
When the app was initially designed, we established a few guiding rules. We do not have a designer helping us so these rules help the app feel cohesive.

The appropriate ruleset here was that, 
- we want the app to be dark-mode first so that it can accommodate the usual work productions work environment
- we do not want to hide any process of the production workflow (no menus or hidden settings, no popups....)
- a part of the app which does not belong to the production workflow (things which are typically set once and not changed during production time. like in this example: view settings, pincodes, integration ports. Could break the above rules, and should be visually distinct. We opted that that distinction would come from its light mode

As a side effect, light mode makes it easier to show larger amounts of text and to build components which was also an advantage.


I am happy to challenge any of the rules, and specifically, this design decision which is not founded in a rule bigger than "be different"
Do you have a suggestion of what these could look like?
What do you feel are the biggest advantages of keeping the entire flow in dark mode? is it just a matter of following guidelines?

Thank you again for bringing this up, I am curious on following up

**Comment by cpvalente** [comment]
Closing this as a stale issue.

Although we understand that it might be nice to have the UI completely dark, at this moment, it seems to offer little benefit.
It would also make us go back to the drawing board and design a new set of components

In my opinion, too much work for not so much gain. Once for v3
