### ISSUE TITLE
Excel upload Backstage URL & End Message not importing.

### ISSUE THREAD

**Issue by EventReplay** [cpvalente/ontime#432]
I'm having a nose round the code but not really understanding whats required!

parser seems the place to start?

**Comment by cpvalente** [comment]
Hi, parser is absolutely the right place to start.
Somewhere around [here ](https://github.com/cpvalente/ontime/blob/master/apps/server/src/utils/parser.ts#L30)

From a quick look in the code everything seems to be fine,
The fields should be called `backstage url` and `end message`

Would you mind providing a screenshot of what you are trying to import?

**Comment by EventReplay** [comment]
![Excel_Schedule](https://github.com/cpvalente/ontime/assets/49799927/5e636645-d22e-466f-a634-a2ebd276bf72)

**Comment by cpvalente** [comment]
Hi @EventReplay , 

That is a very good observation and it seems that this exactly the case. 

Since no other views settings are exposed in excel I will go ahead and remove the end message as well.

This is likely not the resolution you have hoped for but it feels the most pragmatic for now.
Please do feel free to create a new issue with a potential specification for what should an excel import contain
