### ISSUE TITLE
Can't resize in Windows 

### ISSUE THREAD

**Issue by mwolfaardt** [cpvalente/ontime#534]
When I run the application in Windows,.I can't resize it or even scroll.

**Comment by cpvalente** [comment]
> When I run the application in Windows,.I can't resize it or even scroll.

Hi, @mwolfaardt thank you for reaching out.
Can you please add some more detail? 
Which version are you using? What is your monitor resolution?

Can you also add a screenshot of the issue?

**Comment by mwolfaardt** [comment]
Sure
![image](https://github.com/cpvalente/ontime/assets/11614412/97f94c06-1f0f-4b1f-92fb-040bad85f209)

Have a look to the right of the screen, I can't view any details, also under the timer message blink. 

My resolution is pretty high.
![image](https://github.com/cpvalente/ontime/assets/11614412/1758e6ad-c0e0-46c1-b2bd-db26b2a51ce3)

**Comment by cpvalente** [comment]
> Sure
> 
> ![image](https://github.com/cpvalente/ontime/assets/11614412/97f94c06-1f0f-4b1f-92fb-040bad85f209)
> 
> 
> 
> Have a look to the right of the screen, I can't view any details, also under the timer message blink. 
> 
> 
> 
> My resolution is pretty high.
> 
> ![image](https://github.com/cpvalente/ontime/assets/11614412/1758e6ad-c0e0-46c1-b2bd-db26b2a51ce3)
> 
> 

Thank you for this.
The issue seems to be that your scaling is too high. This issue is described in the project README. You can circumvent it by dropping the scaling percentage.
We also have a task to improve scaling in large screens, although it mostly focuses on UWHD, you can follow the progress here 
https://github.com/cpvalente/ontime/issues/477

**Comment by mwolfaardt** [comment]
Thank you, I'll do so
