### ISSUE TITLE
ability to enter posts with just a start time

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#59]
If end time is 0 or - (default) maybe the post can be assumed to only show a start time and calculate the end time

enter start time -> if end time not set by user. set end time to start time of next event dynamically

**Comment by cpvalente** [comment]
Could you take a look at #55 and see if this is inline with the idea of a note event?

You would be able to add an event with a single text field and a start time.
This event shows up in the lists, but is otherwise ignored by the timers

The question here becomes:
- Should this be a workflow of the current event item or a new event type? 

I see that creating a new event type would make it explicit in terms of data structure and workflow. But I understand that it could become annoying to have to transfer data from one event type to another if there is no easy way to convert between event types.

**Comment by xztraz** [comment]
i think the event posts should be usable as before but with an option to just enter a start time. maybe default endtime to a "-" to indicate not set?
And those should be able to be public and work with timers and so on. 
Assume next start time is the end time(for all timers) and just don't show end time in web schedules.
schedule usually just includes start times for a running show. there might be different for a movie set where there are constant pauses.
the collapsed view could contain just start time and expanded all the other options if you want less stuff there.

**Comment by xztraz** [comment]
if entering times is made so end or start time is entered automaticly or tie to start times this function of single time events would not be really needed and the note events would cover other needs

**Comment by cpvalente** [comment]
I can see that we could make it so that events without an end time would only count up. Makes sense.
However I would like to find a holistic approach to this:
- Events with only start, only count up
- Events with only duration only behave normally from the time they are started
- Events with only end, behave normally from the time they are started

You wouldn't be able to add automation to an event with only start

Any thoughts here?

**Comment by cpvalente** [comment]
I believe the new link features are a better solution to this problem
ie: all events still need to have a start, end and duration, but those values can be dynamic

Closing this for now
