### ISSUE TITLE
Save view to URL alias

### ISSUE THREAD

**Issue by kellhogs** [cpvalente/ontime#608]
I really like the new options menu for the views and how this improves workflow with them.
I can imagine users having a favorite way of how they want to display their timer. What if we implement a "Save to URL alias" button which would give the users the ability to save their favorite views and have the easily reproducible when they have to display the on multiple different displays.

This would need us to implement a button in the settings view with maybe a small popup to give it a name. This would then save a new URL alias.

We currently do not check for unique alias names which should probably be added here too.

**Comment by cpvalente** [comment]
Hi @kellhogs, thank you for this suggestion

I think this could be a good improvement for the app. Unsure on the implementation cost
There has been some great work around the configuration of the views done by @asharonbaltazar, maybe he has some opinions?

**Comment by asharonbaltazar** [comment]
The first thing that came to mind was having a third button below the Pencil (Edit) that would display a similar slideout with all the saved URLS for that particular view. The slideout will have a create/edit/delete buttons to manage their saved URLs. The theme will remain consistent. What do you think?

**Comment by kellhogs** [comment]
I really like this approach, although we should think about how we would implement the existing settings menu into this. Or do we ditch it at this point?

Also adding the ability to open saved views from that menu would be good.

**Comment by asharonbaltazar** [comment]
By settings menu, do you mean the customization slideout? I'm thinking either:
- we have two slideouts. One for customizing the view, and one for managing the saved URLs.
- we add a "Saved" tab to the existing customization slideout with all the relevant functionality there

**Comment by kellhogs** [comment]
Sorry for the misunderstanding... I'm talking about the existing URL alias menu in the ontime settings.

**Comment by asharonbaltazar** [comment]
Ah, I think that should be up to @cpvalente to decide

**Comment by cpvalente** [comment]
Maybe it is helpful to understand the scope of the work

### CONTEXT
Currently, the user can customise a view using URL params. The view params helps with this
We also have aliases, which save a view customisation. These are useful for a few scenarios:
- integrations (you dont want to type a long URL)
- sharing a configured view
- saving a view configuration, as some sort of preset manager

In the case where the user has configured a view, they would currently need to copy the URL and paste it in the Alias settings in the `/editor`.

This is the point where we are trying to help the user. I think it is a good feature, but we should keep in mind that the action we are simplifying is already not complex, maybe boring. 
It is important to ensure that our solution doesnt end up being more complex than the problem it solves


### POTENTIAL IMPLEMENTATION
As I see it, we would need something that:
- understand which view is in and filters the existing aliases that affect that view
- allows users to add, load and modify view specific aliases

I imagine that this could be a section at the top of the existing menu. There is definitely a challenge in presenting this in a good way.

We can also take the opportunity to organise the configurations by sections, since we are start accumulating several behaviours 

See below a potential implementation
<img width="689" alt="Screenshot 2023-11-22 at 21 36 05" src="https://github.com/cpvalente/ontime/assets/34649812/5c7f08cb-c072-4bc5-9580-1e27ed148b18">

It would be good to solve two issues which the proposal doesnt:
- how would the user name the new alias?
- how do we link this up to the aliases settings in` /editor`? it is important to make the users aware that this is the same feature


> how we would implement the existing settings menu into this. Or do we ditch it at this point?
I dont think this replaces the usage of the Aliases settings in the main app, since those would relate to the entire application, not view specific

**Comment by asharonbaltazar** [comment]
Guess I'll work on a combination of what I'm thinking and your helpful suggestions, @cpvalente. Assigning to myself

**Comment by cpvalente** [comment]
Hi @kellhogs ,

We took some time to consider this feature.
We have concluded that there are two lines of thoughts suggested here

1. The user can customise a view and create a project wide alias from the customisation parameters
2. The user can create a local preset of the customisation parameters

The decision we reached was that both of these replace operations which are simple enough from the users perspective. In the first case, the user can simply copy the URL and add it to the alias list; in the second case, you can use browser bookmarks

We have decided that we would prioritise other features and improve documentation that clarifies that view configuration are kept in the URL

I apologise if this is not what you would have liked to hear,
Thank you for taking the time to suggest the feature
