### ISSUE TITLE
Crash in roll mode when current time is before start time

### ISSUE THREAD

**Issue by bxtdvd** [cpvalente/ontime#845]
I could very well be doing something wrong, but I'm experiencing a crashing bug on v3.0.0-alpha2 with roll mode.

Steps to reproduce:

1. Create an event that starts _later_ than the current time. For example, it's 15:00:00 right now. Create an event that starts at 16:00:00 with a duration of 1:00:00. 
2. Hit the play icon on the rundown to load that event.
3. Hit the roll icon in the timer control area.
4. App crashes.

(The production situation here is that I might be ahead of the runsheet, but I still want the current event to end at the scheduled time — essentially giving that element extra time).

**Comment by cpvalente** [comment]
Hi @bxtdvd , thank you for this.

I wasnt able to recreate, and assume it might be related to a previous bug about the calculation of offset which has already been fixed.

I am hoping to get a new alpha version out later today, it would be great if you could verify if the issue is gone for you.

As for your production case:

`Roll mode` is, by default, always on time. If you have the following:
```
Clock: 18:00:00
Rundown: 09:00 - 17:00
````
Activating roll mode will start a countdown for tomorrow.

In your use case, you likely want to start playback with the `Play` button and set the timer to `time-to-end`. 
This means: regardless of when it started, I want to count to the end of this event

Hope this helps

**Comment by cpvalente** [comment]
Hi @bxtdvd , could you please verify with the newest alpha release?
I believe all issues in the area have been resolved.
Feel free to check in otherwise

**Comment by bxtdvd** [comment]
Thanks for looking into this. I'm no longer able to reproduce this on the newest alpha release.

I know this is pretty non-specific feedback, but things seem a lot more solid/consistent/reliable on this alpha as far as editing the rundown while the clock is running (changing from countdown to time to end, adding events, changing durations and start/end times, etc.).

I appreciate all your work on this!
