### ISSUE TITLE
V3: Custom Fields get ignored on xslx and google sheets import

### ISSUE THREAD

**Issue by herzogmedia** [cpvalente/ontime#927]
When importing from google sheets or excel files, custom fields can be mapped to corresponding columns in those sheets but do not show up in the import preview window nor are they shown in any view. If custom fields had been manually added through the interface they are removed after import.

Version: 3.0.0-beta.2

**Comment by cpvalente** [comment]
Thank you @herzogmedia , I can confirm that I see the same issue.
I also see that @alex-Arc has been working on some code that will also resolve this bug

As for the second part

> If custom fields had been manually added through the interface they are removed after import.

This is still true, the custom fields are a dataset of the rundown, so when the rundown gets replaced, so do the custom fields.

Without complicating the import process even more with options, what is the expected behaviour here in your opinion?

**Comment by herzogmedia** [comment]
> Without complicating the import process even more with options, what is the expected behaviour here in your opinion?

I just wasn't sure, if ontime expected me to add the custom fields manually before the import or not, so I wanted to clarify that this did not help. For me, it makes much more sense to add the fields during import - just as it is now

**Comment by herzogmedia** [comment]
that was quick ;) with beta.3 (#925 ) it works like a charm now!
