### ISSUE TITLE
Feature Request: Whitelist allow changing end time of event

### ISSUE THREAD

**Issue by admiralchekov** [cpvalente/ontime#970]
I have been using ontime for a while now to manage clocks and timers around a large orchestral recording studio and loving the new workflow improvements in V3!

We use roll mode and often need to update the end time of an event if a break is started early. It would be incredibly helpful if this was possible to do over the APIs as we could then press one button on companion to set the end time of the current event to the current time.

**Comment by cpvalente** [comment]
Thank you @admiralchekov,

We have initially decided to blacklist from the changes API elements which makes us recalculate the rundown.
The idea is that the changes API is made simpler so that you can sync external playback to Ontime data. If this goes rogue there could be some significant issues.

We will take sometime to reconsider.
Do you mind clarifying whether your request is to have API access to the change or companion module support for it?

Meanwhile: all the operations in Ontime are available through an API. Our UI can be completely recreated by users if you wish to do so.
Specifically for changing duration of an event, you will need a `HTTP` `PUT` request with id and a new `duration` value, like:

```ts
fetch("http://localhost:4001/data/rundown", {
  "body": "{"id": "20fbfa","duration":2640000}",
  "method": "PUT"
});
```

Hope this helps

**Comment by 7omas** [comment]
How about allowing this using a setting that is by default off. Maybe even add some kind of verification (passcode)? With a warning notice..

My main reason for asking is that I wish to be able to access all commands using the same protocol (WebSocket) in the Ontime-Chataigne-module.

**Comment by cpvalente** [comment]
> My main reason for asking is that I wish to be able to access all commands using the same protocol (WebSocket) in the Ontime-Chataigne-module.

The requests here seem to focus mostly on modules (chataigne and companion). Coincidentally these are both maintained by Alex

@alex-Arc, would you mind taking a look and suggesting a way forwards?

**Comment by alex-Arc** [comment]
Yes sounds doable
